### ISSUE TITLE
Use that with AdminLTE

### ISSUE THREAD

**Issue by Lukkez** [MastaCoder/MyUsers#3]
This works with adminlte? i'm going to use on a page

**Comment by skyleter** [comment]
LOL xdddd

**Comment by skyleter** [comment]
Ok.
MyUsers includes  login, register, etc etc etc.

Merging it with that panel could take a bit of time. Find just a login form mysql and a register one and then implement to it. Thats what i did. Because MyUsers is... in some words, designed? to be customized, create pages to it. As said, merging it with a panel could take some time.

**Comment by makandz** [comment]
@mogokcp is completely correct.
